### ISSUE TITLE
User Not Registered in Developer Dashboard

### ISSUE THREAD

**Issue by trialskid** [rickystar04/SPDownloader#5]
Good day!

I am trying to use this but i am having the following issue

`Paste playlist link: https://open.spotify.com/playlist/*
HTTP Error for GET to https://api.spotify.com/v1/playlists/*/tracks with Params: {'limit': 100, 'offset': 0, 'fields': None, 'market': None, 'additional_types': 'track'} returned 403 due to User not registered in the Developer Dashboard
HTTP Error for GET to https://api.spotify.com/v1/albums/* with Params: {} returned 403 due to User not registered in the Developer Dashboard
ERRORE: http status: 403, code:-1 - https://api.spotify.com/v1/albums/5h843OjsxOFkLoARkDjzpq:
 User not registered in the Developer Dashboard, reason: None
Traceback (most recent call last):
  File "/Users/*/SPDownloader/spdownloader.py", line 103, in <module>
    main()
  File "/Users/*/SPDownloader/spdownloader.py", line 85, in main
    name, type = song_download(link)
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
`

**Comment by rickystar04** [comment]
Hi! First of all, thank you for using my software.
Now, from what I see in the error reported it would appear that your Spotify account is not enabled as a developer account . Did you follow the steps I reported in the README file?
1)Visit the Spotify Developer Dashboard and log in.
2)Accept the terms of service (if this is your first time logging in).
3)Select "Create an App" and enter any name you want.
4)Copy the Client Id and Client Secret.

**Comment by trialskid** [comment]
I did! I also added myself as a user

**Comment by rickystar04** [comment]
So can you get to this point?
![Screenshot 2023-10-25 224029](https://github.com/rickystar04/SPDownloader/assets/70718835/021a8730-db2c-4f9e-aabb-6f66a036cf96)

**Comment by trialskid** [comment]
Yes, I can.

**Comment by rickystar04** [comment]
Did you change the credentials in the cred.py file?

**Comment by trialskid** [comment]
I did, yes

**Comment by rickystar04** [comment]
I am developing an update to implement a new stocking method for credentials. Between today and tomorrow I should publish it.

**Comment by rickystar04** [comment]
> I did, yes


Could you send me a screenshot of your Spotify Developer dashboard?

**Comment by rickystar04** [comment]
@trialskid I made several changes, try downloading the latest version and see if it works for you now

**Comment by trialskid** [comment]
> @trialskid I made several changes, try downloading the latest version and see if it works for you now

I now get this error when running setup.py

sudo: apt-get: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found
sh: python: command not found

**Comment by rickystar04** [comment]
What operating system and version of Python do you use?

**Comment by trialskid** [comment]
MacOS 14

Python 3.11.6

**Comment by rickystar04** [comment]
Probably the command "python -m ..." is not recognized in macOS. I updated the "setup.py" file using only pip, which in theory should work.
